version: '3.9'

services:
  nest-api:
    container_name: nest-api
    image: 'nest-api:${NODE_ENV}'
    ports:
      - '8081:${PORT_API_PRIVATE}'

  # react-client:
  #   image: 'react-client:${TAG}'
  #   environment:
  #     - API_PATH=http://nest-api:3333
  #   ports:
  #     - '8080:3334'

  npm:
    container_name: npm
    image: npm:util
    # build:
    #   context: .
    #   dockerfile: tools/docker/npm.util.dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/app

  # sample:
  #   container_name: sample
  #   build:
  #     context: .
  #     dockerfile: tools/docker/react-client.dev.dockerfile
  #   volumes:
  #     - '.:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 3001:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
